### ISSUE TITLE
where is your dataset

### ISSUE THREAD

**Issue by gaow0007** [danmohaha/WIFS2018_In_Ictu_Oculi#4]
It is so amazing. Another paper related about head pose estimation detection  test on this dataset. Maybe some authors involve this work too. Your dataset is not released and your code test on this work is not released. 
Such an amazing work!

**Comment by pauloamed** [comment]
Hey. "We collect many videos from Internet and manually annotate the eye state of each frame. Due to the copyright issue, the collected set is not published. Thus I only upload an example in each folder."
